### ISSUE TITLE
hivmmer fails on report generation

### ISSUE THREAD

**Issue by jpflorido** [kantorlab/hivmmer#18]
Hi,
I'm running hivmmer using the conda environment as detailed in the manual, but it fails on report generation:

_hivmmer -o /home/jpflorido/GBPA/tmp/VIH/himmer/ -t 12 DRR030218_1.fastq DRR030218_2.fastq
Creating output directories in:                                                                                                                                                                                    
/home/jpflorido/GBPA/tmp/VIH/himmer                                                                                                                                                                                
Running PEAR on FASTQ inputs:
/home/jpflorido/GBPA/tmp/VIH/DRR030218_1.fastq
/home/jpflorido/GBPA/tmp/VIH/DRR030218_2.fastq
Filtering and deduplicating PEAR sequences
Translating deduplicated sequences to amino acid sequences
Copying pHMM references
Aligning gag with hmmsearch
Aligning pol with hmmsearch
Aligning vif with hmmsearch
Aligning vpr with hmmsearch
Aligning tat with hmmsearch
Aligning vpu with hmmsearch
Aligning env with hmmsearch
Aligning nef with hmmsearch
Extracting codons from hmmsearch alignments
Merging codons across genes
Generating consensus sequences
Generating AA table
Identifying DRMs in AA table
Plotting WGS coverage
Plotting PRRT coverage
Plotting DRMs/SDRMs
Compiling PDF report
Traceback (most recent call last):
  File "/home/jpflorido/miniconda3/envs/hivmmer/bin/hivmmer", line 139, in <module>
    "report", "report.pdf")
  File "/home/jpflorido/miniconda3/envs/hivmmer/lib/python3.7/site-packages/hivmmer/report.py", line 258, in compile
    run(["tectonic", texfile], stdout=f, stderr=f, check=True)
  File "/home/jpflorido/miniconda3/envs/hivmmer/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['tectonic', 'report/report.tex']' returned non-zero exit status 1._

Any suggestions?
Thanks

**Comment by mhowison** [comment]
Hi Javier, it looks like you are missing the tectonic command, which you can install from:

https://tectonic-typesetting.github.io/en-US/

**Comment by jpflorido** [comment]
Hi ,
Thanks for your reply. I'm afraid that the problem persists. Tectonic is installed:

```
(hivmmer) jpflorido@jpflorido-CBRA:~$ tectonic
error: The following required arguments were not provided:
    <INPUT>

USAGE:
    tectonic <INPUT> --chatter <LEVEL> --format <PATH> --outfmt <FORMAT> --pass <PASS>

For more information try --help
```
And the error still appears....
Any suggestions?
Thanks

**Comment by ammaraziz** [comment]
I think the issue is that the path to `report.tex` is not correct. It should be `{output_dir}/report/report.tex` instead of `report/report.tex`.

Another related issue I ran into is that version 1.1 of tectonic uses a now broken link to archive.org (seems to download a required bundle). But the recipe on here is stuck on 1.1.
